---
title: "**Poisson and Negative Binomial Simulations**"
output: html_document
date: '2024-07-24'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# **Simulation Details**

We simulate a matrix $Y \in \mathbb{R}^{n\times p}$ that contains raw expression values (scRNA-seq counts) for $p$ genes and $n$ single cells. We test several conditions. The first is to test a null model that assumes no dispersion using the Poisson distribution. We also test scenarios with different levels of dispersion using the Negative Binomial model.

## **Poisson Distribution**

We first simulate a Poisson distribution as our null model for each gene, where there is no dispersion parameter. The density function is:

$$
f(y;\lambda) = \frac{\lambda^y e^{-\lambda}}{y!}
$$

where for $y =0,1,2,...$ the $E[Y] = Var[Y] = \lambda$. We use the **rpois($n$, $\lambda$)** function in R to simulate the Poisson distribution. 
$$
y_j \sim Pois(\lambda_j) \text{ ,    where } j = 1,\cdots,p
$$

We set $\lambda_j$ equal to the mean gene expression using raw counts from the hybrid data set. Mean gene expression is calculated across cells from the same species, replicate, and cell type. We simulate for $n=500$ cells.

## **Negative Binomial Distribution**

We simulate the Negative Binomial distribution as the the alternative model for each gene. The density function is:

$$
f(y;\mu, \theta) = {y+\theta-1 \choose y} \left(\frac{\mu}{\mu+\theta}\right)^y \left(\frac{\theta}{\mu+\theta}\right)^\theta 
$$
where for $y =0,1,2,...$ the $E[Y] = \mu$ and $Var[Y] = \mu + \frac{\mu^2}{\theta}$. Note that the *dispersion* parameter is $\phi=1/\theta$. We use the **rnegbin($n$, $\mu$, $\theta$)** function from the *MASS* R package to simulate the Negative Binomial distribution.

$$
y_j \sim NB(\mu_j,\theta_j) \text{ ,    where } j = 1,\cdots,p
$$

We set $\mu_j$ equal to the mean gene expression using raw counts from the hybrid data set. Mean gene expression is calculated across cells from the same species, replicate, and cell type. We introduce and test varying dispersion levels for $\phi_j = 1/\theta_j$ and simulate for $n=500$ cells.


